ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
--	12c 버전 이전 문법 허용 구문

CREATE USER a123 IDENTIFIED BY a123;

GRANT resource, CONNECT TO a123;
ALTER USER a123 DEFAULT TABLESPACE system quota unlimited ON system;

--

--테이블 삭제
DROP TABLE TB_MEMBER CASCADE CONSTRAINT ;
DROP TABLE TB_POST  CASCADE CONSTRAINT ;

-- 회원 테이블
CREATE TABLE TB_MEMBER (
	USER_ID NUMBER PRIMARY KEY,
	USERNAME VARCHAR2(100) NOT NULL,
	PASSWORD_HASH VARCHAR2(256) NOT NULL,
	JOIN_DATE DATE DEFAULT SYSDATE
);

-- 게시글/메모 테이블
CREATE TABLE TB_POST (
	POST_ID NUMBER PRIMARY KEY,
	USER_ID NUMBER NOT NULL CONSTRAINT FK_POST_USER REFERENCES TB_MEMBER(USER_ID),
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	MEMO_OPTION NUMBER DEFAULT 0 NOT NULL CHECK (MEMO_OPTION IN (0, 1, 2)),
	MEMO_CHECK NUMBER DEFAULT 0,
	TOPIC VARCHAR2(200) NOT NULL,
	CREATED_AT DATE DEFAULT SYSDATE
);

COMMIT;